[module]
[module.hugoVersion]
extended = true
min = "0.87.0"
max = "0.145.0"

theme = "blowfish"
baseURL = "https://pixelatedpenmanship.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableSearch = true
[pagination]
    pagerSize = 6
[outputs]
    home = ["HTML", "RSS", "JSON"]
